#!/usr/bin/env bash
#
# stage-creds.sh — macOS host script.
#
# Reads the operator's local Claude + OMP credentials, copies them to a
# tmpdir, and writes the absolute paths to a .env file consumed by
# compose.yaml. Idempotent — safe to re-run.
#
# Source pattern: darken/cmd/darken/creds.go (Claude keychain) +
# OMP rig pattern from the plan (copy ~/.omp/agent/agent.db* so SQLite
# WAL/SHM can checkpoint inside the container without touching the
# operator's live state).

set -euo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "stage-creds: only supports macOS (security CLI + ~/.omp default layout)"
  echo "stage-creds: on Linux, edit the .env file manually"
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
RIG_DIR="${REPO_ROOT}/test/integration"
ENV_FILE="${RIG_DIR}/.env"

TMP_ROOT="$(mktemp -d -t sesh-integ-creds.XXXXXX)"
echo "stage-creds: tmpdir=${TMP_ROOT}"

# ── 1. Claude OAuth from macOS Keychain ────────────────────────────────
CLAUDE_CREDS="${TMP_ROOT}/claude-credentials.json"
if security find-generic-password -s "Claude Code-credentials" -w \
     > "${CLAUDE_CREDS}" 2>/dev/null; then
  chmod 600 "${CLAUDE_CREDS}"
  echo "stage-creds: claude OAuth blob → ${CLAUDE_CREDS} ($(wc -c < "${CLAUDE_CREDS}" | tr -d ' ') bytes)"
else
  echo "stage-creds: WARNING — no 'Claude Code-credentials' keychain entry"
  echo "stage-creds: did you sign in to Claude Code on this Mac?"
  exit 2
fi

# ── 2. OMP agent.db (copy, don't bind — SQLite WAL/SHM mutates) ────────
OMP_SRC="${HOME}/.omp/agent"
OMP_DST="${TMP_ROOT}/omp-agent"
if [[ ! -f "${OMP_SRC}/agent.db" ]]; then
  echo "stage-creds: WARNING — ${OMP_SRC}/agent.db not found; have you run omp locally yet?"
  exit 3
fi
mkdir -p "${OMP_DST}"
# Copy db + WAL + SHM if present. Use -a to preserve attrs; the container
# remounts the dir RW.
cp -a "${OMP_SRC}/." "${OMP_DST}/"
chmod 700 "${OMP_DST}"
echo "stage-creds: omp dir → ${OMP_DST} ($(ls "${OMP_DST}" | wc -l | tr -d ' ') files)"

# Quick sanity peek — what auth rows did we copy?
if command -v sqlite3 >/dev/null 2>&1; then
  echo "stage-creds: omp auth rows:"
  sqlite3 "${OMP_DST}/agent.db" \
    "SELECT provider, credential_type FROM auth_credentials;" 2>/dev/null \
    | sed 's/^/  /' || true
fi

# ── 3. Artifacts dir (mounted, not bind-of-tmp so results persist) ─────
ARTIFACTS="${RIG_DIR}/artifacts"
mkdir -p "${ARTIFACTS}"
echo "stage-creds: artifacts dir → ${ARTIFACTS}"

# ── 4. Write .env for compose ──────────────────────────────────────────
cat > "${ENV_FILE}" <<EOF
# Generated by test/integration/scripts/stage-creds.sh — do not commit.
# Re-run that script to refresh.
HOST_CLAUDE_CREDS=${CLAUDE_CREDS}
HOST_OMP_DIR=${OMP_DST}
HOST_ARTIFACTS_DIR=${ARTIFACTS}
SESH_CHANNELS_DIR=${SESH_CHANNELS_DIR:-${HOME}/projects/sesh-channels}
EOF

echo "stage-creds: wrote ${ENV_FILE}"
echo
echo "next:  cd ${RIG_DIR} && docker compose up --build"
echo "       (or:  bash scripts/run.sh)"
